export const testBrews = [
  {
    stage: 1,
    generalInfo: {
      name: "Thanksgiving 2018",
      batchSize: "5 Kegs",
      batchType: "Beer",
      batchNumber: "1",
      ibu: "10",
      srm: "7",
      abv: "8",
      origionalGravity: "90",
      finalGravity: "95",
      brewingDate: "10/1/2018",
      dateSecondary: "10/15/2018",
      dateBottling: "11/15/2018",
    },
    ingredients: "Water, Yeast, Hops, Malt, Other",
    brewingNotes: "First brew in the home setup",
    hopsNotes: "Smelly",
    yeastNotes: "Perfectly Fermented",
    fermentationNotes: "Just as expected",
    keggingNotes: "Filled freezer behind bar",
    tastingNotes: {
      appreance: "Golden",
      aroma: "Hoppy",
      flavor: "Crisp",
      bitterness: "6/10",
      consumerRating:"8/10"
    },
    additionalNotes: "Next year less hops - make more kegs!",
  },
  {
    stage: 1,
    generalInfo: {
      name: "test 2",
      batchSize: "test 2",
      batchType: "test 2",
      batchNumber: "test 2",
      ibu: "test 2",
      srm: "test 2",
      abv: "test 2",
      origionalGravity: "test 2",
      finalGravity: "test 2",
      brewingDate: "test 2",
      dateSecondary: "test 2",
      dateBottling: "test 2",
    },
    ingredients: "test2, test2, test2, test2",
    brewingNotes: "test 2",
    hopsNotes: "test 2",
    yeastNotes: "test 2",
    fermentationNotes: "test 2",
    keggingNotes: "test 2",
    tastingNotes: {
      appreance: "test 2",
      aroma: "test 2",
      flavor: "test 2",
      bitterness: "test 2",
    },
    additionalNotes: "test 2",
  },
];

export const formData = {
  stage: 1,
  generalInfo: {
    name: "",
    batchSize: "",
    batchType: "",
    batchNumber: "",
    ibu: "",
    srm: "",
    abv: "",
    origionalGravity: "",
    finalGravity: "",
    brewingDate: "",
    dateSecondary: "",
    dateBottling: "",
  },
  ingredients: "",
  brewingNotes: "",
  hopsNotes: "",
  yeastNotes: "",
  fermentationNotes: "",
  keggingNotes: "",
  tastingNotes: {
    appreance: "",
    aroma: "",
    flavor: "",
    bitterness: "",
  },
  additionalNotes: "",
}
