const info = [
  {
    stage: 1,
    generalInfo: {
      name: "test",
      batchSize: "test",
      batchType: "test",
      batchNumber: "test",
      ibu: "test",
      srm: "test",
      abv: "test",
      origionalGravity: "test",
      finalGravity: "test",
      brewingDate: "test",
      dateSecondary: "test",
      dateBottling: "test",
    },
    ingredients: "Water, Yeast, Hops",
    brewingNotes: "test",
    hopsNotes: "test",
    yeastNotes: "test",
    fermentationNotes: "test",
    keggingNotes: "test",
    tastingNotes: {
      appreance: "test",
      aroma: "test",
      flavor: "test",
      bitterness: "test",
    },
    additionalNotes: "test",
  },
  {
    stage: 1,
    generalInfo: {
      name: "test 2",
      batchSize: "test 2",
      batchType: "test 2",
      batchNumber: "test 2",
      ibu: "test 2",
      srm: "test 2",
      abv: "test 2",
      origionalGravity: "test 2",
      finalGravity: "test 2",
      brewingDate: "test 2",
      dateSecondary: "test 2",
      dateBottling: "test 2",
    },
    ingredients: "Water, Yeast, Hops",
    brewingNotes: "test 2",
    hopsNotes: "test 2",
    yeastNotes: "test 2",
    fermentationNotes: "test 2",
    keggingNotes: "test 2",
    tastingNotes: {
      appreance: "test 2",
      aroma: "test 2",
      flavor: "test 2",
      bitterness: "test 2",
    },
    additionalNotes: "test 2",
  },
];

export default info;
